# import necessary libraries
from models import create_house, create_rent
import os
from flask import (
    Flask,
    render_template,
    jsonify,
    request,
    redirect)
from sqlalchemy import create_engine
from flask_sqlalchemy import SQLAlchemy
import pandas, sqlite3, csv
import numpy as np

from sqlalchemy.ext.declarative import declarative_base
Base = declarative_base()
from sqlalchemy import Column, Integer, String, Float

# flask setup
app = Flask(__name__)

# app.config['SQLALCHEMY_DATABASE_URI'] = os.environ.get('DATABASE_URL', '') or "sqlite:///db.sqlite"

# Remove tracking modifications
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)

# Establish Connection
engine = create_engine(
'sqlite:///rent_house.sqlite',
connect_args={'check_same_thread': False}
)

conn = engine.connect()

house_df = pandas.read_csv("static/data/house_filtered.csv")
house_df.to_sql("House", conn, if_exists='replace', index=False)

rent_df = pandas.read_csv("static/data/rent_cleaned.csv")
rent_df.to_sql("Rent", conn, if_exists='replace', index=False)

Rent = create_rent(db)
House = create_house(db)

from sqlalchemy.orm import Session
session = Session(bind=engine)

# Route to render index.html template using data from Mongo
@app.route("/")
def home():
    # Return template and data
    return render_template("index.html", title="Rent & House Index Analysis", )
@app.route("/about")
def about():
    # Return template and data
    return render_template("about.html", title="About")

# Route that will trigger the scrape function
@app.route("/models")
def models():

    rent_list = session.query(Rent)
    choices = ["United States",
                        "New York",
                        "Los Angeles-Long Beach-Anaheim",
                        "Chicago",
                        "Dallas-Fort Worth",
                        "Philadelphia",
                        "Houston",
                        "Washington",
                        "Miami-Fort Lauderdale",
                        "Atlanta",
                        "Boston",
                        "San Francisco",
                        "Detroit",
                        "Riverside",
                        "Phoenix",
                        "Seattle",
                        "Minneapolis-St Paul",
                        "San Diego",
                        "St. Louis",
                        "Tampa",
                        "Baltimore",
                        "Denver",
                        "Pittsburgh",
                        "Portland",
                        "Charlotte",
                        "Sacramento",
                        "San Antonio",
                        "Orlando",
                        "Cincinnati",
                        "Cleveland",
                        "Kansas City",
                        "Las Vegas",
                        "Columbus",
                        "Indianapolis",
                        "San Jose",
                        "Austin",
                        "Virginia Beach",
                        "Nashville",
                        "Providence",
                        "Milwaukee",
                        "Jacksonville",
                        "Memphis",
                        "Oklahoma City",
                        "Louisville-Jefferson County",
                        "Hartford",
                        "Richmond",
                        "New Orleans",
                        "Buffalo",
                        "Raleigh",
                        "Birmingham",
                        "Salt Lake City",
                        "Rochester",
                        "Grand Rapids",
                        "Tucson",
                        "Urban Honolulu",
                        "Tulsa",
                        "Fresno",
                        "Worcester",
                        "Stamford",
                        "Albuquerque",
                        "Albany",
                        "Omaha",
                        "New Haven",
                        "Bakersfield",
                        "Knoxville",
                        "Greenville",
                        "Ventura",
                        "Allentown",
                        "El Paso",
                        "Baton Rouge",
                        "Dayton",
                        "McAllen",
                        "Columbia",
                        "Greensboro",
                        "Akron",
                        "North Port-Sarasota-Bradenton",
                        "Little Rock",
                        "Stockton",
                        "Charleston",
                        "Syracuse",
                        "Colorado Springs",
                        "Winston-Salem",
                        "Wichita",
                        "Springfield",
                        "Fort Myers",
                        "Boise City",
                        "Toledo",
                        "Madison",
                        "Lakeland",
                        "Ogden",
                        "Daytona Beach",
                        "Des Moines",
                        "Jackson",
                        "Youngstown",
                        "Augusta",
                        "Scranton",
                        "Harrisburg",
                        "Melbourne",
                        "Chattanooga",
                        "Spokane",
                        "Provo",
                        "Lancaster",
                        "Modesto",
                        "Portland",
                        "Durham",
                        "Santa Rosa",
                        "Lexington",
                        "Lafayette",
                        "Lansing",
                        "Fayetteville",
                        "Pensacola",
                        "Visalia",
                        "Shreveport",
                        "Springfield",
                        "York",
                        "Corpus Christi",
                        "Flint",
                        "Reno",
                        "Asheville",
                        "Port St. Lucie",
                        "Santa Maria-Santa Barbara",
                        "Huntsville",
                        "Fort Wayne",
                        "Salinas",
                        "Vallejo",
                        "Mobile",
                        "Reading",
                        "Brownsville",
                        "Killeen",
                        "Canton",
                        "Beaumont",
                        "Manchester",
                        "Salem",
                        "Anchorage",
                        "Davenport",
                        "Peoria",
                        "Myrtle Beach",
                        "Montgomery",
                        "Salisbury",
                        "Gulfport",
                        "Tallahassee",
                        "Trenton",
                        "Fayetteville",
                        "Hickory",
                        "Huntington",
                        "Eugene",
                        "Rockford",
                        "Savannah",
                        "Ann Arbor",
                        "Ocala",
                        "Kalamazoo",
                        "Naples",
                        "South Bend",
                        "Spartanburg",
                        "Evansville",
                        "Kingsport",
                        "Roanoke",
                        "Green Bay",
                        "Lincoln",
                        "Fort Collins",
                        "Utica",
                        "Columbus",
                        "Boulder",
                        "Lubbock",
                        "Erie",
                        "Fort Smith",
                        "Duluth",
                        "Atlantic City",
                        "New London",
                        "San Luis Obispo",
                        "Gainesville",
                        "Santa Cruz",
                        "Clarksville",
                        "Cedar Rapids",
                        "Merced",
                        "Wilmington",
                        "Kennewick",
                        "Greeley",
                        "Waco",
                        "Olympia",
                        "Amarillo",
                        "Binghamton",
                        "Hagerstown",
                        "Bremerton",
                        "Laredo",
                        "Lynchburg",
                        "Yakima",
                        "Crestview-Fort Walton Beach-Destin",
                        "Topeka",
                        "Macon-Bibb County",
                        "Champaign-Urbana",
                        "Tuscaloosa",
                        "College Station",
                        "Sioux Falls",
                        "Charleston",
                        "Appleton",
                        "Chico",
                        "Charlottesville",
                        "Claremont",
                        "Barnstable Town",
                        "Longview",
                        "Burlington",
                        "Prescott",
                        "Springfield",
                        "Tyler",
                        "Las Cruces",
                        "Fargo",
                        "Houma",
                        "Rochester",
                        "Florence",
                        "Medford",
                        "Lafayette-West Lafayette",
                        "Bellingham",
                        "Lake Havasu City",
                        "Saginaw",
                        "Lake Charles",
                        "Johnson City",
                        "Elkhart",
                        "Yuma",
                        "Racine",
                        "Athens",
                        "Torrington",
                        "St. Cloud",
                        "Hilton Head Island",
                        "Bloomington",
                        "Hilo",
                        "Panama City",
                        "Kingston",
                        "Daphne",
                        "Gainesville",
                        "Warner Robins",
                        "Blacksburg",
                        "Jacksonville",
                        "Redding",
                        "Monroe",
                        "Joplin",
                        "El Centro",
                        "Terre Haute",
                        "Muskegon",
                        "East Stroudsburg",
                        "Sioux City",
                        "Greenville",
                        "Waterloo",
                        "Oshkosh",
                        "Yuba City",
                        "Abilene",
                        "Columbia",
                        "Dover",
                        "Eau Claire",
                        "Janesville",
                        "Jackson",
                        "Punta Gorda",
                        "Bloomington",
                        "Pueblo",
                        "Billings",
                        "Bowling Green",
                        "Bend",
                        "Albany",
                        "Vineland",
                        "Niles",
                        "Kahului",
                        "Ottawa",
                        "State College",
                        "Bangor",
                        "Alexandria",
                        "Decatur",
                        "Hanford",
                        "Iowa City",
                        "Rocky Mount",
                        "Monroe",
                        "Wichita Falls",
                        "Madera",
                        "Jefferson City",
                        "Chambersburg",
                        "Texarkana",
                        "Elizabethtown",
                        "Pottsville",
                        "Wheeling",
                        "Florence",
                        "Grand Junction",
                        "Concord",
                        "Dothan",
                        "Santa Fe",
                        "Johnstown",
                        "Traverse City",
                        "Hattiesburg",
                        "Dalton",
                        "Midland",
                        "Homosassa Springs",
                        "Auburn",
                        "Valdosta",
                        "Coeur d'Alene",
                        "Springfield",
                        "St. George",
                        "Vero Beach",
                        "Odessa",
                        "Napa",
                        "Tupelo",
                        "Battle Creek",
                        "Jamestown",
                        "Eureka",
                        "Rapid City",
                        "Flagstaff",
                        "Wausau",
                        "La Crosse",
                        "Lebanon",
                        "Idaho Falls",
                        "Pittsfield",
                        "Lawton",
                        "Farmington",
                        "Jackson",
                        "Morgantown",
                        "Glens Falls",
                        "Winchester",
                        "St. Joseph",
                        "Altoona",
                        "New Bern",
                        "Carbondale",
                        "London",
                        "Logan",
                        "Harrisonburg",
                        "Beckley",
                        "Mansfield",
                        "Weirton",
                        "Goldsboro",
                        "Augusta",
                        "Hammond",
                        "Jonesboro",
                        "Sherman",
                        "Anniston",
                        "Staunton",
                        "Muncie",
                        "Mount Vernon",
                        "Albany",
                        "Watertown",
                        "Williamsport",
                        "Cleveland",
                        "Sheboygan",
                        "Bismarck",
                        "Owensboro",
                        "Dunn",
                        "Wooster",
                        "Morristown",
                        "Kankakee",
                        "Brunswick",
                        "Ogdensburg",
                        "San Angelo",
                        "Michigan City",
                        "Holland",
                        "Wenatchee",
                        "Lawrence",
                        "Decatur",
                        "Missoula",
                        "Salem",
                        "Bay City",
                        "Lewiston",
                        "Roseburg",
                        "Sumter",
                        "Meridian",
                        "Show Low",
                        "Bluefield",
                        "Danville",
                        "Lima",
                        "Cookeville",
                        "California-Lexington Park",
                        "Gadsden",
                        "Cumberland",
                        "Longview",
                        "Whitewater",
                        "Fond du Lac",
                        "Ithaca",
                        "Ashtabula",
                        "Gettysburg",
                        "Pine Bluff",
                        "Tullahoma",
                        "Richmond",
                        "Adrian",
                        "Twin Falls",
                        "Corning",
                        "Sebring",
                        "Truckee",
                        "Paducah",
                        "Grand Forks",
                        "Shelby",
                        "Fairbanks",
                        "Ocean City",
                        "Mankato",
                        "Rome",
                        "Cape Girardeau",
                        "Hot Springs",
                        "Greenwood",
                        "Sunbury",
                        "Clarksburg",
                        "Talladega",
                        "Dubuque",
                        "The Villages",
                        "Albertville",
                        "Manhattan",
                        "Parkersburg",
                        "New Philadelphia",
                        "Orangeburg",
                        "Cheyenne",
                        "New Castle",
                        "Brainerd",
                        "Kalispell",
                        "Sevierville",
                        "Ames",
                        "Bozeman",
                        "Moses Lake",
                        "Indiana",
                        "Elmira",
                        "Meadville",
                        "Beaver Dam",
                        "Pinehurst-Southern Pines",
                        "Ukiah",
                        "Hermiston-Pendleton",
                        "Lufkin",
                        "Zanesville",
                        "Corvallis",
                        "Bloomsburg",
                        "Laurel",
                        "Russellville",
                        "Branson",
                        "Watertown",
                        "Midland",
                        "Opelousas",
                        "Pocatello",
                        "Kokomo",
                        "Grants Pass",
                        "Huntsville",
                        "Plattsburgh",
                        "Grand Island",
                        "DuBois",
                        "Danville",
                        "Manitowoc",
                        "Great Falls",
                        "Wilson",
                        "Cullman",
                        "Olean",
                        "Auburn",
                        "Portsmouth",
                        "Athens",
                        "Oak Harbor",
                        "Chillicothe",
                        "Hinesville",
                        "Somerset",
                        "Warsaw",
                        "Stillwater",
                        "Quincy",
                        "Keene",
                        "Sandusky",
                        "Searcy",
                        "Columbus",
                        "Roanoke Rapids",
                        "Centralia",
                        "Casper",
                        "Helena",
                        "Findlay",
                        "Wisconsin Rapids-Marshfield",
                        "Palatka",
                        "Seneca",
                        "Mount Airy",
                        "Glenwood Springs",
                        "Aberdeen",
                        "Gallup",
                        "Port Angeles",
                        "Greenfield Town",
                        "Muskogee",
                        "Frankfort",
                        "Owosso",
                        "Mount Pleasant",
                        "Statesboro",
                        "Marion",
                        "Stevens Point",
                        "Minot",
                        "Shawnee",
                        "North Wilkesboro",
                        "Richmond",
                        "Greeneville",
                        "Martinsville",
                        "Forest City",
                        "Lake City",
                        "Kapaa",
                        "Marquette",
                        "LaGrange",
                        "Marion",
                        "Morehead City",
                        "Marinette",
                        "Roswell",
                        "Marshall",
                        "Farmington",
                        "Charleston",
                        "Athens",
                        "Hobbs",
                        "Clearlake",
                        "Nacogdoches",
                        "Hutchinson",
                        "Faribault",
                        "Elizabeth City",
                        "Ionia",
                        "Red Bluff",
                        "Hudson",
                        "Somerset",
                        "Coos Bay",
                        "Walla Walla",
                        "Sayre",
                        "Oneonta",
                        "Fort Madison",
                        "Baraboo",
                        "Marietta",
                        "Salina",
                        "Rutland",
                        "Big Stone Gap",
                        "Sturgis",
                        "Rio Grande City",
                        "Fremont",
                        "Mount Vernon",
                        "Lewiston",
                        "Shelton",
                        "Albemarle",
                        "Enid",
                        "Jefferson",
                        "Georgetown",
                        "Laconia",
                        "Batavia",
                        "Oxford",
                        "Columbus",
                        "Norwalk",
                        "Barre",
                        "Kinston",
                        "Sterling",
                        "Palestine",
                        "Dublin",
                        "Vicksburg",
                        "Point Pleasant",
                        "Sanford",
                        "Fergus Falls",
                        "Tiffin",
                        "Fairmont",
                        "Crossville",
                        "Picayune",
                        "Gloversville",
                        "Gaffney",
                        "Carson City",
                        "Calhoun",
                        "Milledgeville",
                        "Waycross",
                        "Oil City",
                        "Jasper",
                        "Morgan City",
                        "Eagle Pass",
                        "Ontario",
                        "Payson",
                        "McComb",
                        "Rochelle",
                        "Scottsboro",
                        "Danville",
                        "Ashland",
                        "Natchez",
                        "Greenville",
                        "Galesburg",
                        "Warrensburg",
                        "Kearney",
                        "Fort Polk South",
                        "Fort Leonard Wood",
                        "Glasgow",
                        "Athens",
                        "Edwards",
                        "Fernley",
                        "Mason City",
                        "Malone",
                        "Winona",
                        "Durango",
                        "Platteville",
                        "Boone",
                        "Bartlesville",
                        "Jacksonville",
                        "Elko",
                        "Rexburg",
                        "St. Marys",
                        "Ozark",
                        "Amsterdam",
                        "Enterprise",
                        "Paris",
                        "Kerrville",
                        "New Castle",
                        "Sidney",
                        "Cortland",
                        "Clinton",
                        "Del Rio",
                        "Norfolk",
                        "Washington",
                        "Corsicana",
                        "Freeport",
                        "Starkville",
                        "Burlington",
                        "Cadillac",
                        "Ardmore",
                        "Kendallville",
                        "Nogales",
                        "Oxford",
                        "Bogalusa",
                        "Plymouth",
                        "Gardnerville Ranchos",
                        "Tahlequah",
                        "Madisonville",
                        "Ruston",
                        "Hillsdale",
                        "Lewistown",
                        "Rockingham",
                        "Ponca City",
                        "Blytheville",
                        "Red Wing",
                        "Shawano",
                        "Cedar City",
                        "Bedford",
                        "Gillette",
                        "Newport",
                        "Wapakoneta",
                        "Huntingdon",
                        "Bellefontaine",
                        "McAlester",
                        "Blackfoot",
                        "Moultrie",
                        "Henderson",
                        "Coldwater",
                        "Harrison",
                        "Rolla",
                        "Shelbyville",
                        "Duncan",
                        "Marion",
                        "Lewisburg",
                        "Pullman",
                        "Thomasville",
                        "Bemidji",
                        "Mount Sterling",
                        "Ottumwa",
                        "Pahrump",
                        "Menomonie",
                        "Selma",
                        "Rock Springs",
                        "Bucyrus",
                        "Bradford",
                        "Bardstown",
                        "Cornelia",
                        "Burley",
                        "Greenwood",
                        "Big Rapids",
                        "Poplar Bluff",
                        "Muscatine",
                        "Alma",
                        "Durant",
                        "Seymour",
                        "Douglas",
                        "Willmar",
                        "Auburn",
                        "Sedalia",
                        "Paragould",
                        "Wilmington",
                        "Lawrenceburg",
                        "Warren",
                        "El Dorado",
                        "Mountain Home",
                        "Cedartown",
                        "Port Clinton",
                        "El Campo",
                        "Montrose",
                        "Ellensburg",
                        "Jacksonville",
                        "Sandpoint",
                        "Alice",
                        "Celina",
                        "Garden City",
                        "Marshalltown",
                        "Aberdeen",
                        "West Plains",
                        "Cullowhee",
                        "Espa±ola",
                        "Riverton",
                        "Tifton",
                        "Urbana",
                        "Cambridge",
                        "Okeechobee",
                        "McMinnville",
                        "Selinsgrove",
                        "Natchitoches",
                        "Berlin",
                        "Lock Haven",
                        "Sikeston",
                        "Austin",
                        "Clewiston",
                        "Pittsburg",
                        "Defiance",
                        "Scottsbluff",
                        "Logansport",
                        "Pontiac",
                        "Hannibal",
                        "Mount Vernon",
                        "Houghton",
                        "Union City",
                        "Sault Ste. Marie",
                        "Vincennes",
                        "Gainesville",
                        "Dyersburg",
                        "Kill Devil Hills",
                        "Crawfordsville",
                        "Brownwood",
                        "Stephenville",
                        "Americus",
                        "Easton",
                        "North Platte",
                        "Newberry",
                        "Ada",
                        "Moscow",
                        "Safford",
                        "Murray",
                        "Bennington",
                        "Huntington",
                        "Mayfield",
                        "Escanaba",
                        "Canton",
                        "Corinth",
                        "Astoria",
                        "Peru",
                        "Coshocton",
                        "Newton",
                        "Logan",
                        "Bay City",
                        "Fremont",
                        "Hutchinson",
                        "Batesville",
                        "Owatonna",
                        "Vidalia",
                        "Summit Park",
                        "Arkansas City-Winfield",
                        "Laramie",
                        "Plainview",
                        "Big Spring",
                        "Laurinburg",
                        "Dixon",
                        "Alexandria",
                        "Newport",
                        "DeRidder",
                        "Lebanon",
                        "Coffeyville",
                        "Seneca Falls",
                        "Martin",
                        "Susanville",
                        "Brookhaven",
                        "Arcadia",
                        "Taylorville",
                        "Decatur",
                        "Junction City",
                        "Effingham",
                        "Valley",
                        "Butte",
                        "Angola",
                        "Dodge City",
                        "Brenham",
                        "Emporia",
                        "Jackson",
                        "Frankfort",
                        "Brevard",
                        "Taos",
                        "Malvern",
                        "Troy",
                        "Wabash",
                        "Cambridge",
                        "Macomb",
                        "Vernal",
                        "Kingsville",
                        "Madison",
                        "Mount Pleasant",
                        "Paris",
                        "Columbus",
                        "Brookings",
                        "Kennett",
                        "Beeville",
                        "Miami",
                        "Dayton",
                        "Washington",
                        "Camden",
                        "Jackson",
                        "Hastings",
                        "Juneau",
                        "Albert Lea",
                        "Lewisburg",
                        "Iron Mountain",
                        "Lincoln",
                        "Jesup",
                        "Kirksville",
                        "Alpena",
                        "Silver City",
                        "Elkins",
                        "Las Vegas",
                        "McPherson",
                        "Sheridan",
                        "Washington Court House",
                        "Bennettsville",
                        "Van Wert",
                        "Merrill",
                        "Ludington",
                        "Middlesborough",
                        "Crescent City",
                        "North Vernon",
                        "Hays",
                        "Forrest City",
                        "Fort Morgan",
                        "Mineral Wells",
                        "Breckenridge",
                        "Bastrop",
                        "Bainbridge",
                        "Wauchula",
                        "Hailey",
                        "Great Bend",
                        "Weatherford",
                        "Watertown",
                        "Grants",
                        "Thomaston",
                        "Mountain Home",
                        "Altus",
                        "Uvalde",
                        "Lexington",
                        "Boone",
                        "Toccoa",
                        "Clarksdale",
                        "Summerville",
                        "Ottawa",
                        "New Ulm",
                        "Marshall",
                        "La Grande",
                        "Greensburg",
                        "Mexico",
                        "Moberly",
                        "The Dalles",
                        "Deming",
                        "Fallon",
                        "Fredericksburg",
                        "Magnolia",
                        "Campbellsville",
                        "Connersville",
                        "Dickinson",
                        "Spearfish",
                        "Heber",
                        "Steamboat Springs",
                        "Cordele",
                        "Marshall",
                        "Maryville",
                        "Arkadelphia",
                        "Liberal",
                        "Levelland",
                        "Wahpeton",
                        "Mitchell",
                        "Sterling",
                        "Pampa",
                        "Yankton",
                        "Williston",
                        "Oskaloosa",
                        "Brookings",
                        "Hood River",
                        "Beatrice",
                        "Borger",
                        "Raymondville",
                        "Elk City",
                        "Dumas",
                        "Helena",
                        "Price",
                        "Port Lavaca",
                        "Worthington",
                        "Pierre",
                        "Evanston",
                        "Jamestown",
                        "Prineville",
                        "Storm Lake",
                        "Woodward",
                        "Portales",
                        "Hereford",
                        "Othello",
                        "Los Alamos",
                        "Fitzgerald",
                        "Maysville",
                        "Huron",
                        "Atchison",
                        "Snyder",
                        "Fairfield",
                        "Spencer",
                        "Spirit Lake",
                        "Vineyard Haven",
                        "Winnemucca",
                        "Sweetwater",
                        "Andrews",
                        "Zapata",
                        "Vermillion",
                        "Lamesa",
                        "Craig",
                        "Vernon",
                        "Ketchikan"
                    ]
    # Redirect back to home page
    return render_template("models.html", title="Models", rent=rent_list, choices=choices)

@app.route("/housemap")
def housemap():

    # Redirect back to home page
    return render_template("housemap.html", title="House Index Density Map")

@app.route("/rentmap")
def rentmap():

    # Redirect back to home page
    return render_template("rentmap.html", title="Rent Index Density Map")

@app.route("/api/rent_data")
def rent_data():

    results = session.query(Rent.RegionId, Rent.State, Rent.City, Rent.Lat, Rent.Lng, Rent.Year, Rent.Month, Rent.Price).all()

    RegionId = [result[0] for result in results]
    State = [result[1] for result in results]
    City = [result[2] for result in results]
    Lat = [result[3] for result in results]
    Lng = [result[4] for result in results]
    Year = [result[5] for result in results]
    Month = [result[6] for result in results]
    Price = [result[7] for result in results]

    rent_data = [{
        "RegionId": RegionId,
        "State": State,
        "City": City,
        "Lat": Lat,
        "Lng": Lng,
        "Year": Year,
        "Month": Month,
        "Price": Price
    }]

    return jsonify(rent_data)

@app.route("/api/house_data")
def house_data():

    results = session.query(House.RegionId, House.State, House.City, House.Lat, House.Lng, House.Year, House.Month, House.Price).all()

    RegionId = [result[0] for result in results]
    State = [result[1] for result in results]
    City = [result[2] for result in results]
    Lat = [result[3] for result in results]
    Lng = [result[4] for result in results]
    Year = [result[5] for result in results]
    Month = [result[6] for result in results]
    Price = [result[7] for result in results]

    house_data = [{
        "RegionId": RegionId,
        "State": State,
        "City": City,
        "Lat": Lat,
        "Lng": Lng,
        "Year": Year,
        "Month": Month,
        "Price": Price
    }]

    return jsonify(house_data)

@app.route("/api/house_data/1/2020/")
def jan_twentytwenty_data():

    results = session.query(House.RegionId, House.State, House.City, House.Lat, House.Lng, House.Year, House.Month, House.Price).all()

    RegionId = [result[0] for result in results if result[6] == 1 if result[5] == 2020 if result[7] >= 309433]
    State = [result[1] for result in results if result[6] == 1 if result[5] == 2020 if result[7] >= 309433]
    City = [result[2] for result in results if result[6] == 1 if result[5] == 2020 if result[7] >= 309433]
    Lat = [result[3] for result in results if result[6] == 1 if result[5] == 2020 if result[7] >= 309433]
    Lng = [result[4] for result in results if result[6] == 1 if result[5] == 2020 if result[7] >= 309433]
    Year = [result[5] for result in results if result[6] == 1 if result[5] == 2020 if result[7] >= 309433]
    Month = [result[6] for result in results if result[6] == 1 if result[5] == 2020 if result[7] >= 309433]
    Price = [result[7] for result in results if result[6] == 1 if result[5] == 2020 if result[7] >= 309433]

    heatmap_data = [{
        "RegionId": RegionId,
        "State": State,
        "City": City,
        "Lat": Lat,
        "Lng": Lng,
        "Year": Year,
        "Month": Month,
        "Price": Price
    }]

    return jsonify(heatmap_data)

@app.route("/api/rent_data/1/2020/")
def jan_twentytwenty_rent_data():

    results = session.query(Rent.RegionId, Rent.State, Rent.City, Rent.Lat, Rent.Lng, Rent.Year, Rent.Month, Rent.Price).all()

    RegionId = [result[0] for result in results if result[6] == 1 if result[5] == 2020 if result[7] >= 1691]
    State = [result[1] for result in results if result[6] == 1 if result[5] == 2020 if result[7] >= 1691]
    City = [result[2] for result in results if result[6] == 1 if result[5] == 2020 if result[7] >= 1691]
    Lat = [result[3] for result in results if result[6] == 1 if result[5] == 2020 if result[7] >= 1691]
    Lng = [result[4] for result in results if result[6] == 1 if result[5] == 2020 if result[7] >= 1691]
    Year = [result[5] for result in results if result[6] == 1 if result[5] == 2020 if result[7] >= 1691]
    Month = [result[6] for result in results if result[6] == 1 if result[5] == 2020 if result[7] >= 1691]
    Price = [result[7] for result in results if result[6] == 1 if result[5] == 2020 if result[7] >= 1691]

    heatmap_data = [{
        "RegionId": RegionId,
        "State": State,
        "City": City,
        "Lat": Lat,
        "Lng": Lng,
        "Year": Year,
        "Month": Month,
        "Price": Price
    }]

    return jsonify(heatmap_data)

@app.route("/api/house_data/bubblechart")
def house_bubblechart():

    results = session.query(House.RegionId, House.City, House.Year, House.Price, House.Month).all()

    City = [result[1] for result in results if result[4] == 12 if result[2] == 2014]
    Year = [result[2] for result in results if result[4] == 12 if result[2] == 2014]
    Price_2014 = [result[3] for result in results if result[4] == 12 if result[2] == 2014]
    Price_2020 = [result[3] for result in results if result[4] == 12 if result[2] == 2020]

    #limiting the data sets to top 250 cities
    City = City[:250]
    Year = Year[:250]
    Price_2014 = Price_2014[:250]
    Price_2020 = Price_2020[:250]

    #subtract each 2014 list element from each corresponding 2020 list element, divide the result by 1000, then round that result to 0 decimal places
    PriceChange = (np.subtract(Price_2020,Price_2014)/1000).tolist()

    house_bubblechart_data = [{
        "City": City,
        "Year": Year,
        "Price": Price_2020,
        "MarkerSize": PriceChange
    }]

    return jsonify(house_bubblechart_data)

if __name__ == "__main__":
    app.run()